import type { Metadata } from "next";
import "./styles/globals.css";
import { Nunito } from "next/font/google";
import MainLayout from "@/app/layouts/MainLayout";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { ThemeProvider } from "next-themes";

const nunito = Nunito({
  subsets: ["latin"],
  weight: "200",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();

  return (
    <html suppressHydrationWarning className={nunito.className} lang={locale}>
      <body>
        <ThemeProvider defaultTheme="light" attribute="class">
          <NextIntlClientProvider locale={locale} messages={messages}>
            {/* Layout UI */}
            <MainLayout>{children}</MainLayout>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
